In [1]:
import numpy as np
from numpy.random import default_rng

# NumPy Array
* questions gathered @ https://github.com/tfvieira/deep-learning/blob/main/src/numpy_tutorial/readme.md

1. _How to create an empty and a full NumPy array?_

In [3]:
# Empty array
print(np.array([]))

# Full array
print('\n', np.full((2,2),10))

[]

 [[10 10]
 [10 10]]


2. _Create a Numpy array filled with all zeros_ <br>
&& <br>
3. _Create a Numpy array filled with all ones_

In [4]:
# 1-D array filled with zeros
print(np.zeros(4))

# 2-D array filled with ones
print('\n', np.ones((4,4)))

[0. 0. 0. 0.]

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


4. _Check whether a Numpy array contains a specified row_

In [5]:
arr = np.array([i for i in range(20)]).reshape((4,5))
ex1_row = list(range(5,10))
ex2_row = list(range(11,20))
print(f'the np array:\n{arr}\n\nthe specified rows: {ex1_row, ex2_row}')
print(f'result (is in nparray): {ex1_row in arr.tolist(), ex2_row in arr.tolist()}')

the np array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

the specified rows: ([5, 6, 7, 8, 9], [11, 12, 13, 14, 15, 16, 17, 18, 19])
result (is in nparray): (True, False)


5. _How to Remove rows in Numpy array that contains non-numeric values?_

In [10]:
arr = np.array([
    [np.nan,5,6,7],
    [8,9,10,np.nan],
    [11,12,13,14]
])
arr = arr[~np.isnan(arr).any(axis=1)]
arr

array([[11., 12., 13., 14.]])

6. _Remove single-dimensional entries from the shape of an array_

In [8]:
np.squeeze(np.arange(8).reshape(2,2,2))

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

7. _Find the number of occurrences of a sequence in a NumPy array_

In [17]:
arr = np.full((3,3), [5,7,1])
print(f'array:\n{arr}\nquantidade de (7,1):\n{repr(arr).count("7, 1")}')

array:
[[5 7 1]
 [5 7 1]
 [5 7 1]]
quantidade de (7,1):
3


8. _Find the most frequent value in a NumPy array_

In [25]:
arr = np.array([2,4,6,4,5,8,2,2,1,7])
np.bincount(arr).argmax()

2

9. _Combining a one and a two-dimensional NumPy Array_

In [28]:
arr_2d = np.arange(10).reshape(2,5)
np.vstack((np.arange(5), arr_2d))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

10. _How to build an array of all combinations of two NumPy arrays?_

In [42]:
np.array(np.meshgrid(arr, arr_2d)).T.reshape(-1,2)

array([[2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4],
       [2, 5],
       [2, 6],
       [2, 7],
       [2, 8],
       [2, 9],
       [4, 0],
       [4, 1],
       [4, 2],
       [4, 3],
       [4, 4],
       [4, 5],
       [4, 6],
       [4, 7],
       [4, 8],
       [4, 9],
       [6, 0],
       [6, 1],
       [6, 2],
       [6, 3],
       [6, 4],
       [6, 5],
       [6, 6],
       [6, 7],
       [6, 8],
       [6, 9],
       [4, 0],
       [4, 1],
       [4, 2],
       [4, 3],
       [4, 4],
       [4, 5],
       [4, 6],
       [4, 7],
       [4, 8],
       [4, 9],
       [5, 0],
       [5, 1],
       [5, 2],
       [5, 3],
       [5, 4],
       [5, 5],
       [5, 6],
       [5, 7],
       [5, 8],
       [5, 9],
       [8, 0],
       [8, 1],
       [8, 2],
       [8, 3],
       [8, 4],
       [8, 5],
       [8, 6],
       [8, 7],
       [8, 8],
       [8, 9],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4],
       [2, 5],
       [2,

11. _How to add a border around a NumPy array?_

In [50]:
np.pad(np.full((3,3),7), pad_width=2, mode='constant', constant_values=0)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 7, 7, 0, 0],
       [0, 0, 7, 7, 7, 0, 0],
       [0, 0, 7, 7, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

12. _How to compare two NumPy arrays?_

In [52]:
arr = np.array([22,16,53])
arr_2 = np.array([28,18,56])

print(f'arrays:\n{arr}\n{arr_2}\n')
print(f'>\n{np.greater(arr, arr_2)}\n<\n{np.less(arr, arr_2)}\n>=\n{np.greater_equal(arr, arr_2)}\n<=\n{np.less_equal(arr, arr_2)}')

arrays:
[22 16 53]
[28 18 56]

>
[False False False]
<
[ True  True  True]
>=
[False False False]
<=
[ True  True  True]


13. _How to check whether specified values are present in NumPy array?_

In [55]:
print(f'array:\n{arr_2d}\n9 está contido no array?\n{9 in arr_2d}')

array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
9 está contido no array?
True


14. _How to get all 2D diagonals of a 3D NumPy array?_

In [61]:
arr_3d = np.arange(2*2*2).reshape(2,2,2)
print(f'array:\n{arr_3d}\n\ndiagonais:\n{np.diagonal(arr_3d, axis1=1, axis2=2)}')

array:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

diagonais:
[[0 3]
 [4 7]]


15. _Flatten a Matrix in Python using NumPy_<br>
&&<br>
16. _Flatten a 2d numpy array into 1d array_

In [69]:
print(f'matrix:\n{arr_2d}\nflattened:\n{arr_2d.flatten()}')

matrix:
[[0 1 2 3 4]
 [5 6 7 8 9]]
flattened:
[0 1 2 3 4 5 6 7 8 9]


17. _Move axes of an array to new positions_

In [78]:
arr = np.moveaxis(arr_3d,-1,0)
print(f'array:\n{arr_3d.reshape(4,2)}\ndepois:\n{arr}')

array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
depois:
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]


18. _Interchange two axes of an array_

In [80]:
np.swapaxes(arr,1,0)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

19. _NumPy – Fibonacci Series using Binet Formula_

In [83]:
lo_bound, hi_bound = 5, 15
arr = np.arange(lo_bound, hi_bound)
sz = len(arr)
sqrt = np.sqrt(5)
alpha = (1 + sqrt) / 2
beta = (1 - sqrt) / 2
Fn = np.rint(((alpha ** arr) - (beta ** arr)) / (sqrt))
print(f'número de fibonacci entre a {lo_bound} e a {hi_bound} posição:\n{Fn}')

número de fibonacci entre a 5 e a 15 posição:
[  5.   8.  13.  21.  34.  55.  89. 144. 233. 377.]


20. _Counts the number of non-zero values in the array_

In [86]:
print(f'array:\n{arr}\nnon-zeros:\n{np.count_nonzero(arr)}')

array:
[ 5  6  7  8  9 10 11 12 13 14]
non-zeros:
10


21. _Count the number of elements along a given axis_

In [89]:
print(f'array:\n{arr_2d}\nnum de linhas: {np.size(arr_2d,0)}\nnum de cols: {np.size(arr_2d,1)}')
print(f'num de elementos: {np.size(arr_2d)}')

array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
num de linhas: 2
num de cols: 5
num de elementos: 10


22. _Trim the leading and/or trailing zeros from a 1-D array_

In [95]:
padd = np.pad(arr, pad_width=2)
print(f'array:\n{padd}\nfinal:\n{np.trim_zeros(padd)}')

array:
[ 0  0  5  6  7  8  9 10 11 12 13 14  0  0]
final:
[ 5  6  7  8  9 10 11 12 13 14]


23. _Change data type of given numpy array_

In [102]:
print(f'array:\n{arr_2}\ntipo: {arr_2.dtype}')
arr_2 = arr_2.astype('float64')
print(f'as float:\n{arr_2}\ntipo: {arr_2.dtype}')

array:
[28 18 56]
tipo: int64
as float:
[28. 18. 56.]
tipo: float64


24. _Reverse a numpy array_

In [100]:
print(f'array:\n{arr_3d}\n\nflipped:\n{np.flip(arr_3d)}')

array:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

flipped:
[[[7 6]
  [5 4]]

 [[3 2]
  [1 0]]]


25. _How to make a NumPy array read-only?_

In [107]:
ones = np.ones(4).astype(int)
ones.flags.writeable = False
ones[4] = 1

ValueError: assignment destination is read-only

# Numpy matrix

# Numpy indexing

# Numpy Linear Algebra

1. _Find a matrix or vector norm using NumPy_

In [6]:
# vector norm
arr = np.arange(15)
print(f'array:\n{arr}\narray norm: {np.linalg.norm(arr)}')

# matrix norm
arr = arr.reshape((5,3))
print(f'\n\nmatrix:\n{arr}\nmatrix norm: {np.linalg.norm(arr)}')

array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
array norm: 31.85906464414798


matrix:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
matrix norm: 31.85906464414798


2. _Calculate the QR decomposition of a given matrix using NumPy_

In [8]:
q, r = np.linalg.qr(arr)
print(f'Q:\n{q}\n\nR: {r}')

Q:
[[ 0.00000000e+00 -7.74596669e-01 -2.44775605e-01]
 [-1.82574186e-01 -5.16397779e-01  1.36693675e-01]
 [-3.65148372e-01 -2.58198890e-01 -1.01215083e-01]
 [-5.47722558e-01  8.32667268e-16  7.71451562e-01]
 [-7.30296743e-01  2.58198890e-01 -5.62154549e-01]]

R: [[-1.64316767e+01 -1.82574186e+01 -2.00831604e+01]
 [ 0.00000000e+00 -1.29099445e+00 -2.58198890e+00]
 [ 0.00000000e+00  0.00000000e+00  1.61656869e-15]]


3. _Compute the condition number of a given matrix using NumPy_

In [9]:
print(f'matrix:\n{arr}\ncondition number: {np.linalg.cond(arr)}')

matrix:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
condition number: 4.821066647629074e+16


4. _Compute the eigenvalues and right eigenvectors of a given square array using NumPy_

In [13]:
arr = np.array([[1, 2, 3],
              [2, 3, 4],
              [4, 5, 6]])
w, v = np.linalg.eig(arr)
print(f'eigenvalues:\n{w}\n\neigenvectors:\n{v}')

eigenvalues:
[ 1.08309519e+01 -8.30951895e-01  1.01486082e-16]

eigenvectors:
[[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]


5. _Calculate the Euclidean distance using NumPy_

In [33]:
import time
p1 = np.array([15,22,1])
p2 = np.array([72,0,0])
minus = p2-p1

# pure euclidean formula
start = time.time()
calc = np.sqrt(np.sum(np.square(minus)))
end = time.time()
print(f'sqrt(sum(square(minus(p2-p1)))):\n{calc}\nexec time: {(end-start)*10**3}ms')

# using dot product
start = time.time()
calc = np.sqrt(np.dot(minus.T, minus))
end = time.time()
print(f'\nsqrt(dot(p2-p1)):\n{calc}\nexec time: {(end-start)*10**3}ms')

# using the minus vector norm
start = time.time()
calc = np.linalg.norm(minus)
end = time.time()
print(f'\nnorm(p2-p1):\n{calc}\nexec time: {(end-start)*10**3}ms')

sqrt(sum(square(minus(p2-p1)))):
61.106464469808756
exec time: 0.087738037109375ms

sqrt(dot(p2-p1)):
61.106464469808756
exec time: 0.11944770812988281ms

norm(p2-p1):
61.106464469808756
exec time: 0.09775161743164062ms


# Numpy random

# Sorting and Searching

# Mathematics

# Statistics

# Polynomial

# Strings