# NumPy Array
* this is a college assignment (https://github.com/tfvieira/deep-learning/blob/main/src/numpy_tutorial/readme.md)

In [29]:
import numpy as np
from numpy.random import default_rng

1. _How to create an empty and a full NumPy array?_

In [13]:
# Creating a empty array by instanciating the np.array class
print(np.array([]))

# The easiest way to create a filled array is to fill it with regularly incrementing values
print('\n', np.arange(10))

[]

 [0 1 2 3 4 5 6 7 8 9]


2. _Create a Numpy array filled with all zeros_ <br>
&& <br>
3. _Create a Numpy array filled with all ones_

In [10]:
# 1-D array filled with zeros
print(np.zeros(4))

# 2-D array filled with ones
print('\n', np.ones((4,4)))

[0. 0. 0. 0.]

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


4. _Check whether a Numpy array contains a specified row_

In [45]:
# The following approach uses the inbuilt library function to compare as python classic lists
arr = np.array([i for i in range(20)]).reshape((4,5))
ex1_row = list(range(5,10))
ex2_row = list(range(11,20))
print(f'the np array:\n{arr}\n\nthe specified rows: {ex1_row, ex2_row}')
print(f'result (is in nparray): {ex1_row in arr.tolist(), ex2_row in arr.tolist()}')

the np array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

the specified rows: ([5, 6, 7, 8, 9], [11, 12, 13, 14, 15, 16, 17, 18, 19])
result (is in nparray): (True, False)


5. _How to Remove rows in Numpy array that contains non-numeric values?_

In [62]:
# Create a slice of the array only if the condition is not met
# TODO recognize string as non-numeric
arr = np.array([
    [np.nan,5,6,7],
    [8,9,10,np.nan],
    [11,12,13,14]
])
arr[~np.isnan(arr).any(axis=1)]

array([[11., 12., 13., 14.]])