In [30]:
import numpy as np

* questions gathered @ https://github.com/tfvieira/deep-learning/blob/main/src/numpy_tutorial/readme.md

# NumPy Array

1. _How to create an empty and a full NumPy array?_

In [31]:
# Empty array
print(np.array([]))

# Full array
print('\n', np.full((2,2),10))

[]

 [[10 10]
 [10 10]]


2. _Create a Numpy array filled with all zeros_ <br>
&& <br>
3. _Create a Numpy array filled with all ones_

In [32]:
# 1-D array filled with zeros
print(np.zeros(4))

# 2-D array filled with ones
print('\n', np.ones((4,4)))

[0. 0. 0. 0.]

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


4. _Check whether a Numpy array contains a specified row_

In [33]:
arr = np.array([i for i in range(20)]).reshape((4,5))
ex1_row = list(range(5,10))
ex2_row = list(range(11,20))
print(f'the np array:\n{arr}\n\nthe specified rows: {ex1_row, ex2_row}')
print(f'result (is in nparray): {ex1_row in arr.tolist(), ex2_row in arr.tolist()}')

the np array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

the specified rows: ([5, 6, 7, 8, 9], [11, 12, 13, 14, 15, 16, 17, 18, 19])
result (is in nparray): (True, False)


5. _How to Remove rows in Numpy array that contains non-numeric values?_

In [34]:
arr = np.array([
    [np.nan,5,6,7],
    [8,9,10,np.nan],
    [11,12,13,14]
])
arr = arr[~np.isnan(arr).any(axis=1)]
arr

array([[11., 12., 13., 14.]])

6. _Remove single-dimensional entries from the shape of an array_

In [35]:
np.squeeze(np.arange(8).reshape(2,2,2))

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

7. _Find the number of occurrences of a sequence in a NumPy array_

In [36]:
arr = np.full((3,3), [5,7,1])
print(f'array:\n{arr}\nquantidade de (7,1):\n{repr(arr).count("7, 1")}')

array:
[[5 7 1]
 [5 7 1]
 [5 7 1]]
quantidade de (7,1):
3


8. _Find the most frequent value in a NumPy array_

In [37]:
arr = np.array([2,4,6,4,5,8,2,2,1,7])
np.bincount(arr).argmax()

2

9. _Combining a one and a two-dimensional NumPy Array_

In [38]:
arr_2d = np.arange(10).reshape(2,5)
np.vstack((np.arange(5), arr_2d))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

10. _How to build an array of all combinations of two NumPy arrays?_

In [39]:
np.array(np.meshgrid(arr, arr_2d)).T.reshape(-1,2)

array([[2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4],
       [2, 5],
       [2, 6],
       [2, 7],
       [2, 8],
       [2, 9],
       [4, 0],
       [4, 1],
       [4, 2],
       [4, 3],
       [4, 4],
       [4, 5],
       [4, 6],
       [4, 7],
       [4, 8],
       [4, 9],
       [6, 0],
       [6, 1],
       [6, 2],
       [6, 3],
       [6, 4],
       [6, 5],
       [6, 6],
       [6, 7],
       [6, 8],
       [6, 9],
       [4, 0],
       [4, 1],
       [4, 2],
       [4, 3],
       [4, 4],
       [4, 5],
       [4, 6],
       [4, 7],
       [4, 8],
       [4, 9],
       [5, 0],
       [5, 1],
       [5, 2],
       [5, 3],
       [5, 4],
       [5, 5],
       [5, 6],
       [5, 7],
       [5, 8],
       [5, 9],
       [8, 0],
       [8, 1],
       [8, 2],
       [8, 3],
       [8, 4],
       [8, 5],
       [8, 6],
       [8, 7],
       [8, 8],
       [8, 9],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4],
       [2, 5],
       [2,

11. _How to add a border around a NumPy array?_

In [40]:
np.pad(np.full((3,3),7), pad_width=2, mode='constant', constant_values=0)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 7, 7, 0, 0],
       [0, 0, 7, 7, 7, 0, 0],
       [0, 0, 7, 7, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

12. _How to compare two NumPy arrays?_

In [41]:
arr = np.array([22,16,53])
arr_2 = np.array([28,18,56])

print(f'arrays:\n{arr}\n{arr_2}\n')
print(f'>\n{np.greater(arr, arr_2)}\n<\n{np.less(arr, arr_2)}\n>=\n{np.greater_equal(arr, arr_2)}\n<=\n{np.less_equal(arr, arr_2)}')

arrays:
[22 16 53]
[28 18 56]

>
[False False False]
<
[ True  True  True]
>=
[False False False]
<=
[ True  True  True]


13. _How to check whether specified values are present in NumPy array?_

In [42]:
print(f'array:\n{arr_2d}\n9 está contido no array?\n{9 in arr_2d}')

array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
9 está contido no array?
True


14. _How to get all 2D diagonals of a 3D NumPy array?_

In [43]:
arr_3d = np.arange(2*2*2).reshape(2,2,2)
print(f'array:\n{arr_3d}\n\ndiagonais:\n{np.diagonal(arr_3d, axis1=1, axis2=2)}')

array:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

diagonais:
[[0 3]
 [4 7]]


15. _Flatten a Matrix in Python using NumPy_<br>
&&<br>
16. _Flatten a 2d numpy array into 1d array_

In [44]:
print(f'matrix:\n{arr_2d}\nflattened:\n{arr_2d.flatten()}')

matrix:
[[0 1 2 3 4]
 [5 6 7 8 9]]
flattened:
[0 1 2 3 4 5 6 7 8 9]


17. _Move axes of an array to new positions_

In [45]:
arr = np.moveaxis(arr_3d,-1,0)
print(f'array:\n{arr_3d.reshape(4,2)}\ndepois:\n{arr}')

array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
depois:
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]


18. _Interchange two axes of an array_

In [46]:
np.swapaxes(arr,1,0)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

19. _NumPy – Fibonacci Series using Binet Formula_

In [47]:
lo_bound, hi_bound = 5, 15
arr = np.arange(lo_bound, hi_bound)
sz = len(arr)
sqrt = np.sqrt(5)
alpha = (1 + sqrt) / 2
beta = (1 - sqrt) / 2
Fn = np.rint(((alpha ** arr) - (beta ** arr)) / (sqrt))
print(f'número de fibonacci entre a {lo_bound} e a {hi_bound} posição:\n{Fn}')

número de fibonacci entre a 5 e a 15 posição:
[  5.   8.  13.  21.  34.  55.  89. 144. 233. 377.]


20. _Counts the number of non-zero values in the array_

In [48]:
print(f'array:\n{arr}\nnon-zeros:\n{np.count_nonzero(arr)}')

array:
[ 5  6  7  8  9 10 11 12 13 14]
non-zeros:
10


21. _Count the number of elements along a given axis_

In [49]:
print(f'array:\n{arr_2d}\nnum de linhas: {np.size(arr_2d,0)}\nnum de cols: {np.size(arr_2d,1)}')
print(f'num de elementos: {np.size(arr_2d)}')

array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
num de linhas: 2
num de cols: 5
num de elementos: 10


22. _Trim the leading and/or trailing zeros from a 1-D array_

In [50]:
padd = np.pad(arr, pad_width=2)
print(f'array:\n{padd}\nfinal:\n{np.trim_zeros(padd)}')

array:
[ 0  0  5  6  7  8  9 10 11 12 13 14  0  0]
final:
[ 5  6  7  8  9 10 11 12 13 14]


23. _Change data type of given numpy array_

In [51]:
print(f'array:\n{arr_2}\ntipo: {arr_2.dtype}')
arr_2 = arr_2.astype('float64')
print(f'as float:\n{arr_2}\ntipo: {arr_2.dtype}')

array:
[28 18 56]
tipo: int64
as float:
[28. 18. 56.]
tipo: float64


24. _Reverse a numpy array_

In [52]:
print(f'array:\n{arr_3d}\n\nflipped:\n{np.flip(arr_3d)}')

array:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

flipped:
[[[7 6]
  [5 4]]

 [[3 2]
  [1 0]]]


25. _How to make a NumPy array read-only?_

In [53]:
ones = np.ones(4).astype(int)
ones.flags.writeable = False
ones[4] = 1

ValueError: assignment destination is read-only

# Numpy matrix

# Numpy indexing

# Numpy Linear Algebra

1. _Find a matrix or vector norm using NumPy_

In [ ]:
# vector norm
arr = np.arange(15)
print(f'array:\n{arr}\narray norm: {np.linalg.norm(arr)}')

# matrix norm
arr = arr.reshape((5,3))
print(f'\n\nmatrix:\n{arr}\nmatrix norm: {np.linalg.norm(arr)}')

array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
array norm: 31.85906464414798


matrix:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
matrix norm: 31.85906464414798


2. _Calculate the QR decomposition of a given matrix using NumPy_

In [ ]:
q, r = np.linalg.qr(arr)
print(f'Q:\n{q}\n\nR: {r}')

Q:
[[ 0.00000000e+00 -7.74596669e-01 -2.44775605e-01]
 [-1.82574186e-01 -5.16397779e-01  1.36693675e-01]
 [-3.65148372e-01 -2.58198890e-01 -1.01215083e-01]
 [-5.47722558e-01  8.32667268e-16  7.71451562e-01]
 [-7.30296743e-01  2.58198890e-01 -5.62154549e-01]]

R: [[-1.64316767e+01 -1.82574186e+01 -2.00831604e+01]
 [ 0.00000000e+00 -1.29099445e+00 -2.58198890e+00]
 [ 0.00000000e+00  0.00000000e+00  1.61656869e-15]]


3. _Compute the condition number of a given matrix using NumPy_

In [ ]:
print(f'matrix:\n{arr}\ncondition number: {np.linalg.cond(arr)}')

matrix:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
condition number: 4.821066647629074e+16


4. _Compute the eigenvalues and right eigenvectors of a given square array using NumPy_

In [ ]:
arr = np.array([[1, 2, 3],
              [2, 3, 4],
              [4, 5, 6]])
w, v = np.linalg.eig(arr)
print(f'eigenvalues:\n{w}\n\neigenvectors:\n{v}')

eigenvalues:
[ 1.08309519e+01 -8.30951895e-01  1.01486082e-16]

eigenvectors:
[[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]


5. _Calculate the Euclidean distance using NumPy_

In [ ]:
import time
p1 = np.array([15,22,1])
p2 = np.array([72,0,0])
minus = p2-p1

# pure euclidean formula
start = time.time()
calc = np.sqrt(np.sum(np.square(minus)))
end = time.time()
print(f'sqrt(sum(square(minus(p2-p1)))):\n{calc}\nexec time: {(end-start)*10**3}ms')

# using dot product
start = time.time()
calc = np.sqrt(np.dot(minus.T, minus))
end = time.time()
print(f'\nsqrt(dot(p2-p1)):\n{calc}\nexec time: {(end-start)*10**3}ms')

# using the minus vector norm
start = time.time()
calc = np.linalg.norm(minus)
end = time.time()
print(f'\nnorm(p2-p1):\n{calc}\nexec time: {(end-start)*10**3}ms')

sqrt(sum(square(minus(p2-p1)))):
61.106464469808756
exec time: 0.087738037109375ms

sqrt(dot(p2-p1)):
61.106464469808756
exec time: 0.11944770812988281ms

norm(p2-p1):
61.106464469808756
exec time: 0.09775161743164062ms


# Numpy random

1. _Create a Numpy array with random values_

In [ ]:
rnd_arr = np.random.random(5)
rnd_arr

array([0.98663861, 0.00649751, 0.18584338, 0.39895361, 0.8746303 ])

2. _How to choose elements from the list with different probability using NumPy?_ <br>
&& <br>
3. _How to get weighted random choice in Python?_

In [ ]:
np.random.choice(rnd_arr, 2, p=[0.2,0.3,0.125,0.125,0.25])

array([0.18584338, 0.00649751])

4. _Generate Random Numbers From The Uniform Distribution using NumPy_

In [ ]:
np.random.uniform(0,6,8)

array([4.63916359, 2.71647898, 5.51871982, 5.85532248, 2.32614847,
       2.7214022 , 4.97053134, 3.83144603])

5. _Get Random Elements form geometric distribution_

In [ ]:
np.random.geometric(p=0.35, size=10)

array([5, 1, 1, 3, 4, 4, 2, 7, 3, 4])

6. _Get Random elements from Laplace distribution_

In [ ]:
np.random.laplace(0., 1., 10)

array([ 1.51744305, -1.621709  ,  3.72518125, -1.13355335, -0.28139428,
       -0.04352957, -0.93542949,  0.86472429,  0.54695696, -0.89463136])

7. _Return a Matrix of random values from a uniform distribution_

In [ ]:
np.random.random((3,3))

array([[0.72041385, 0.66078085, 0.06907273],
       [0.65451305, 0.17375787, 0.98558216],
       [0.75372095, 0.69732964, 0.4945126 ]])

8. _Return a Matrix of random values from a Gaussian distribution_

In [ ]:
np.random.normal(0, 0.1, 10)

array([ 0.01486403, -0.10852463, -0.11293165,  0.11988489, -0.07768016,
        0.00331734, -0.03217821, -0.00609738, -0.21765715, -0.03191784])

# Sorting and Searching

1. _How to get the indices of the sorted array using NumPy in Python?_ <br>
&& <br>
6 _Find the indices into a sorted array_

In [ ]:
arr = np.trim_zeros(np.vstack([p1,p2]).reshape(-1))
print(f'array:\n{arr}\nsorted array indexes: {np.argsort(arr)}')

array:
[15 22  1 72]
sorted array indexes: [2 0 1 3]


2. _Finding the k smallest values of a NumPy array_

In [ ]:
arr = np.vstack((arr, np.random.randint(2, 100, 4))).flatten()
k = 3

sort_idx = np.argsort(arr)
print(f'original array: {arr}\n{k} smallest elements indexes: {sort_idx[:k]}')

original array: [15 22  1 72 51 40 57 67]
3 smallest elements indexes: [2 0 1]


3. _How to get the n-largest values of an array using NumPy?_

In [ ]:
# SAME AS PREVIOUS QUESTION
n = 2
print(f'original array: {arr}\n{n} largest elements indexes: {sort_idx[-n:]}')

original array: [15 22  1 72 51 40 57 67]
2 largest elements indexes: [7 3]


4. _Sort the values in a matrix_

In [ ]:
arr = arr.reshape((4,2))
np.matrix.sort(arr)
arr

array([[ 1, 22],
       [15, 51],
       [40, 67],
       [57, 72]])

5. _Filter out integers from float numpy array_

In [ ]:
farr = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
mask = np.isclose(farr, farr.astype(int))
print(f'array:\n{farr}\n\nresult:\n{farr[~mask]}')

array:
[1.  1.2 2.2 2.  3.  2. ]

result:
[1.2 2.2]


# Mathematics

# Statistics

1. _Compute the median of the flattened NumPy array_

In [60]:
print(f'array: {arr}\nmedian: {np.median(arr)}')

array: [ 5  6  7  8  9 10 11 12 13 14]
median: 9.5


2. _Find Mean of a List of Numpy Array_

In [67]:
print(f'array: {arr}\nmean: {np.mean(arr)}')

array: [ 2.  3.  7.  8. nan nan  1.]
mean: nan


3. _Calculate the mean of array ignoring the NaN value_

In [72]:
arr = np.array([2,3,7,8,np.nan, np.nan, 1])
print(f'array: {arr}\nmean: {np.nanmean(arr)}')

array: [ 2.  3.  7.  8. nan nan  1.]
mean: 4.2


4. _Get the mean value from given matrix_

In [65]:
mat = np.matrix(np.arange(12).reshape((3, 4)))
print(f'matrix: {mat}\nmean: {mat.mean()}')

matrix: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
mean: 5.5


5. _Compute the variance of the NumPy array_

In [78]:
print(f'array: {arr_2}\nvariance: {np.var(arr_2)}')

array: [28. 18. 56.]
variance: 258.6666666666667


6. _Compute the standard deviation of the NumPy array_

In [79]:
print(f'array: {arr_2}\nstd deviation: {np.std(arr_2)}')

array: [28. 18. 56.]
std deviation: 16.08311744241976


7. _Compute pearson product-moment correlation coefficients of two given NumPy arrays_

In [82]:
np.corrcoef(arr_2, np.array([4,45,22]))

array([[ 1.      , -0.321144],
       [-0.321144,  1.      ]])

8. _Calculate the mean across dimension in a 2D NumPy array_

In [83]:
print(f'matrix: {mat}\nmean: {mat.mean(1)}')

matrix: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
mean: [[1.5]
 [5.5]
 [9.5]]


9. _Calculate the average, variance and standard deviation in Python using NumPy_

In [84]:
# done previously in this section

10. _Describe a NumPy Array in Python_

In [85]:
# ???

# Polynomial

1. _Define a polynomial function_

In [ ]:
from numpy.polynomial import polynomial as P
p = P.Polynomial([3,2,1])
p

Polynomial([3., 2., 1.], domain=[-1,  1], window=[-1,  1], symbol='x')

2. _How to add one polynomial to another using NumPy in Python?_

In [ ]:
p2 = (1,1,2)
p3 = P.polyadd(p, p2)
p3

array([Polynomial([4., 2., 1.], domain=[-1.,  1.], window=[-1.,  1.], symbol='x'),
       1, 2], dtype=object)

3. _How to subtract one polynomial to another using NumPy in Python?_

In [ ]:
p4 = P.polysub(p3,p)
p4

array([Polynomial([1.], domain=[-1.,  1.], window=[-1.,  1.], symbol='x'),
       1, 2], dtype=object)

4. _How to multiply a polynomial to another using NumPy in Python?_

In [ ]:
P.polymul(p2, p3)

array([Polynomial([4., 2., 1.], domain=[-1.,  1.], window=[-1.,  1.], symbol='x'),
       Polynomial([5., 2., 1.], domain=[-1.,  1.], window=[-1.,  1.], symbol='x'),
       Polynomial([11.,  4.,  2.], domain=[-1.,  1.], window=[-1.,  1.], symbol='x'),
       4, 4], dtype=object)

5. _How to divide a polynomial to another using NumPy in Python?_

In [ ]:
P.polydiv(p4,p2)

(array([1.0], dtype=object),
 array([Polynomial([0.], domain=[-1.,  1.], window=[-1.,  1.], symbol='x')],
       dtype=object))

6. _Find the roots of the polynomials using NumPy_

In [ ]:
P.polyroots(p2)

array([-0.25-0.66143783j, -0.25+0.66143783j])

7. _Evaluate a 2-D polynomial series on the Cartesian product_

In [ ]:
P.polygrid2d(2,3,1)

1.0

8. _Evaluate a 3-D polynomial series on the Cartesian product_

In [ ]:
P.polygrid3d(2,3,1,2)

2.0

# Strings